services:
  - type: web
    name: yalta-alerts-mvp
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false
      - key: VAPID_SUBJECT
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
